FROM python:3.8-slim-buster

WORKDIR /bookmarks/

RUN apt-get update \
    && apt-get install --no-install-recommends -qy wait-for-it \
    && rm -rf /var/lib/apt/list/*

RUN pip install poetry

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false
RUN poetry install

COPY . .