version: '3.7'

services:
  db:
    image: postgres:13.0
    env_file:
      - .env
    ports:
      - 15432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
    image: bookmarks:local
    user: root
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/bookmarks/
    entrypoint:
      - invoke
      - wait-for
      - db:5432
      - migrate
      - runserver
      - --debug

volumes:
  postgres_data:
