# Generated by Django 3.1.4 on 2020-12-29 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("markers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="last_time_visited",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
