# Generated by Django 3.1.4 on 2020-12-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urls',
            options={'managed': True},
        ),
    ]
