# Generated by Django 3.1.4 on 2021-02-07 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_bookmark_last_time_visited'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_visited', models.SmallIntegerField(default=0)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markers.bookmark')),
            ],
        ),
    ]
