# Generated by Django 3.1.4 on 2021-02-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markers", "0003_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="icon",
            field=models.URLField(default=""),
        ),
    ]
